### ISSUE TITLE
add and remove methods dynamic

### ISSUE THREAD

**Issue by SOVLOOKUP** [organicdesign/libp2p-rpc#1]
Now the addition of methods is one-time, we cannot dynamically add and remove methods during the runtime, but libp2p actually provides an interface that can dynamically add and delete handles

**Comment by saul-jb** [comment]
Libp2p provides an interface for handling and removing handlers for streams running a certain protocol, this module runs on a single stream and runs an RPC protocol over it.

You actually can add methods at runtime, however you were right in that removing them at runtime was not possible. I have implemented removing methods at runtime in version `0.2.0`.

**Comment by SOVLOOKUP** [comment]
I made this: https://github.com/SOVLOOKUP/metapoint/tree/master/packages/libp2p-transport
